site_name: Using Kamal 2.0 in Production
repo_url: https://github.com/rubys/kamal-in-production/
edit_uri: blob/master/docs/

nav:
  - Home:
    - Cover: index.md
    - Preface: Preface.md
    - Introduction: Introduction.md
  - First Deploy:
    - Local: Local.md
    - Assemble: Assemble.md
    - Recipe: Recipe.md
    - Secrets: Secrets.md
    - Storage: Storage.md
    - Deploy: Deploy.md
  - Going to Production:
    - Secure: Secure.md
    - Backup: Backup.md
    - Monitoring: Monitoring.md
    - Thruster: Thruster.md
    - Staging: Staging.md
    - CD: CD.md
    - Scaling: Scaling.md
  - Conclusion:
    - Recap: Recap.md
    - PaaS: PaaS.md
    - Epilogue: Epilogue.md
    
extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.tracking

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins: []